version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: pharmauser
      POSTGRES_PASSWORD: pharmapass
      POSTGRES_DB: pharmadb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "src/scrape_telegram.py"]
volumes:
  pgdata: 