pharma_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5433
      user: pharmauser
      password: pharmapass
      dbname: pharmadb
      schema: analytics
      threads: 4 